In [103]:
from sklearn.datasets import load_iris
import pandas as pd

In [104]:
iris = load_iris()
df = pd.DataFrame(iris.data)
df.columns = iris.feature_names
df['TARGET'] = iris.target

In [105]:
df.head(8)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),TARGET
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0

In [106]:
df['TARGET'].unique()

array([0, 1, 2], dtype=int64)

In [107]:
from sklearn.preprocessing import StandardScaler

In [125]:
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
#In layman's terms, fit_transform means to do some calculation and then do transformation 
#(say calculating the means of columns from some data and then replacing the missing values). 
#So for training set, you need to both calculate and do transformation.
X_test = sc_x.transform(X_test)
#But for testing set, Machine learning applies prediction based on what was learned during 
#the training set and so it doesn't need to calculate, it just performs the transformation.

In [126]:
X_train

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.56381749e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.86480506e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12644135e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31208072e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38312788e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -7.98707650e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31208072e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.85334584e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41411549e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.63981441e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.56381749e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
         7.41411549e-01],
       [-3.30414999e-01, -1.27067995e+00,  5.77759173e-02,
        -1.56991317e-01],
       [ 2.09056967e+00, -1.19254753e-01,  1.28501609e+00,
         1.38312788e+00],
       [ 4.76579890e-01,  5.71600368e-01,  5.04045072e-01,
         4.84725016e-01],
       [-4.45699984e-01, -1.50096499e+00,  1.99227301e-03,
        -1.56991317e-01],
       [ 4.76579890e-01, -8.10109874e-01,  6.15612361e-01,
         7.41411549e-01],
       [ 4.76579890e-01, -5.79824834e-01,  7.27179649e-01,
         3.56381749e-01],
       [-1.13740989e+00, -1.27067995e+00,  3.92477783e-01,
         6.13068282e-01],
       [ 4.76579890e-01, -1.27067995e+00,  6.71396005e-01,
         8.69754815e-01],
       [ 1.28357478e+00,  3.41315328e-01,  5.04045072e-01,
         2.28038483e-01],
       [ 7.07149859e-01, -1.19254753e-01,  7.82963294e-01,
         9.98098082e-01],
       [ 1.30724937e-01,  8.01885408e-01,  3.92477783e-01,
         4.84725016e-01],
       [-1.25269487e+00,  1.11030287e-01, -1.22524790e+00,
        -1.31208072e+00],
       [-9.98450310e-02, -8.10109874e-01,  7.27179649e-01,
         8.69754815e-01],
       [-3.30414999e-01, -8.10109874e-01,  2.25126850e-01,
         9.96952160e-02],
       [-3.30414999e-01, -3.49539793e-01, -1.09575016e-01,
         9.96952160e-02],
       [-4.45699984e-01, -1.27067995e+00,  1.13559562e-01,
         9.96952160e-02],
       [ 2.46009922e-01, -1.19254753e-01,  4.48261428e-01,
         2.28038483e-01],
       [ 1.51414475e+00,  3.41315328e-01,  1.22923245e+00,
         7.41411549e-01],
       [-6.76269952e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31208072e+00],
       [-1.82911979e+00, -1.19254753e-01, -1.50416612e+00,
        -1.44042398e+00],
       [ 5.91864874e-01, -8.10109874e-01,  8.38746938e-01,
         8.69754815e-01],
       [-2.15130015e-01, -1.19254753e-01,  2.25126850e-01,
        -2.86480506e-02],
       [-5.60984968e-01,  8.01885408e-01, -1.16946426e+00,
        -1.31208072e+00],
       [-2.15130015e-01,  3.10473581e+00, -1.28103155e+00,
        -1.05539418e+00],
       [ 1.16828980e+00,  1.11030287e-01,  6.15612361e-01,
         3.56381749e-01],
       [-1.48326484e+00,  1.11030287e-01, -1.28103155e+00,
        -1.31208072e+00],
       [ 1.54399532e-02, -1.19254753e-01,  7.27179649e-01,
         7.41411549e-01],
       [-9.06839920e-01, -1.27067995e+00, -4.44276882e-01,
        -1.56991317e-01],
       [-1.48326484e+00,  8.01885408e-01, -1.33681519e+00,
        -1.18373745e+00],
       [ 3.61294906e-01, -1.96153508e+00,  3.92477783e-01,
         3.56381749e-01],
       [ 1.51414475e+00,  1.26245549e+00,  1.28501609e+00,
         1.63981441e+00],
       [-2.15130015e-01, -3.49539793e-01,  2.25126850e-01,
         9.96952160e-02],
       [-1.25269487e+00, -1.19254753e-01, -1.33681519e+00,
        -1.44042398e+00],
       [ 1.39885976e+00, -1.19254753e-01,  1.17344880e+00,
         1.12644135e+00],
       [ 1.16828980e+00,  3.41315328e-01,  1.06188152e+00,
         1.38312788e+00],
       [ 7.07149859e-01, -1.19254753e-01,  1.11766516e+00,
         1.25478461e+00],
       [ 5.91864874e-01, -5.79824834e-01,  1.00609787e+00,
         1.12644135e+00],
       [-9.06839920e-01,  1.72302557e+00, -1.22524790e+00,
        -1.31208072e+00],
       [-1.25269487e+00,  8.01885408e-01, -1.22524790e+00,
        -1.31208072e+00],
       [ 7.07149859e-01,  3.41315328e-01,  7.27179649e-01,
         9.98098082e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.12644135e+00],
       [-1.59854983e+00, -1.73125004e+00, -1.39259884e+00,
        -1.18373745e+00],
       [ 3.61294906e-01,  8.01885408e-01,  8.94530582e-01,
         1.38312788e+00],
       [-1.13740989e+00, -1.19254753e-01, -1.33681519e+00,
        -1.31208072e+00],
       [-2.15130015e-01, -1.27067995e+00,  6.71396005e-01,
         9.98098082e-01],
       [ 1.16828980e+00,  1.11030287e-01,  8.94530582e-01,
         1.12644135e+00],
       [-1.71383481e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31208072e+00],
       [-1.02212490e+00,  1.26245549e+00, -1.33681519e+00,
        -1.31208072e+00],
       [ 1.51414475e+00, -1.19254753e-01,  1.11766516e+00,
         4.84725016e-01],
       [-9.06839920e-01,  1.03217045e+00, -1.33681519e+00,
        -1.18373745e+00],
       [-1.71383481e+00, -1.19254753e-01, -1.39259884e+00,
        -1.31208072e+00],
       [-5.60984968e-01,  1.95331061e+00, -1.16946426e+00,
        -1.05539418e+00],
       [-4.45699984e-01, -1.73125004e+00,  1.13559562e-01,
         9.96952160e-02],
       [ 1.05300481e+00,  3.41315328e-01,  1.17344880e+00,
         1.38312788e+00],
       [ 1.97528468e+00, -1.19254753e-01,  1.56393431e+00,
         1.12644135e+00],
       [-9.06839920e-01,  1.03217045e+00, -1.33681519e+00,
        -1.31208072e+00],
       [-1.13740989e+00,  1.11030287e-01, -1.28103155e+00,
        -1.44042398e+00],
       [-7.91554936e-01,  8.01885408e-01, -1.33681519e+00,
        -1.31208072e+00],
       [-2.15130015e-01, -5.79824834e-01,  3.92477783e-01,
         9.96952160e-02],
       [ 8.22434843e-01, -1.19254753e-01,  3.36694139e-01,
         2.28038483e-01],
       [-1.02212490e+00,  3.41315328e-01, -1.44838248e+00,
        -1.31208072e+00],
       [-9.06839920e-01,  5.71600368e-01, -1.16946426e+00,
        -9.27050916e-01],
       [ 5.91864874e-01, -3.49539793e-01,  2.80910495e-01,
         9.96952160e-02],
       [-5.60984968e-01,  8.01885408e-01, -1.28103155e+00,
        -1.05539418e+00],
       [ 2.09056967e+00, -1.04039491e+00,  1.73128525e+00,
         1.38312788e+00],
       [-1.13740989e+00, -1.50096499e+00, -2.76925949e-01,
        -2.85334584e-01],
       [ 2.32113964e+00,  1.72302557e+00,  1.45236703e+00,
         9.98098082e-01],
       [ 9.37719827e-01,  1.11030287e-01,  3.36694139e-01,
         2.28038483e-01],
       [-7.91554936e-01,  2.41388069e+00, -1.28103155e+00,
        -1.44042398e+00],
       [ 1.30724937e-01, -1.19254753e-01,  5.59828716e-01,
         7.41411549e-01],
       [-9.98450310e-02,  2.18359565e+00, -1.44838248e+00,
        -1.31208072e+00],
       [ 2.09056967e+00, -5.79824834e-01,  1.61971796e+00,
         9.98098082e-01],
       [-9.06839920e-01,  1.72302557e+00, -1.28103155e+00,
        -1.18373745e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.22524790e+00,
        -1.31208072e+00],
       [ 1.74471472e+00, -5.79824834e-01,  1.28501609e+00,
         8.69754815e-01],
       [-1.02212490e+00,  5.71600368e-01, -1.33681519e+00,
        -1.31208072e+00],
       [ 4.76579890e-01,  8.01885408e-01,  1.00609787e+00,
         1.51147115e+00],
       [-2.15130015e-01, -5.79824834e-01,  1.69343206e-01,
         9.96952160e-02],
       [-9.98450310e-02, -8.10109874e-01,  5.77759173e-02,
        -2.86480506e-02],
       [-2.15130015e-01, -1.04039491e+00, -1.65358660e-01,
        -2.85334584e-01],
       [ 5.91864874e-01,  3.41315328e-01,  8.38746938e-01,
         1.38312788e+00],
       [ 9.37719827e-01, -1.19254753e-01,  7.82963294e-01,
         1.38312788e+00],
       [ 4.76579890e-01, -1.27067995e+00,  6.15612361e-01,
         3.56381749e-01],
       [ 9.37719827e-01, -1.19254753e-01,  6.71396005e-01,
         6.13068282e-01],
       [-1.02212490e+00, -1.19254753e-01, -1.22524790e+00,
        -1.31208072e+00],
       [-4.45699984e-01, -1.50096499e+00, -5.37913713e-02,
        -2.85334584e-01],
       [ 9.37719827e-01,  1.11030287e-01,  1.00609787e+00,
         1.51147115e+00],
       [-9.98450310e-02, -8.10109874e-01,  7.27179649e-01,
         8.69754815e-01],
       [-9.06839920e-01,  8.01885408e-01, -1.28103155e+00,
        -1.31208072e+00],
       [ 8.22434843e-01, -3.49539793e-01,  4.48261428e-01,
         9.96952160e-02],
       [-3.30414999e-01, -1.19254753e-01,  1.69343206e-01,
         9.96952160e-02],
       [ 1.54399532e-02,  3.41315328e-01,  5.59828716e-01,
         7.41411549e-01],
       [ 4.76579890e-01, -1.73125004e+00,  3.36694139e-01,
         9.96952160e-02],
       [-4.45699984e-01,  1.03217045e+00, -1.39259884e+00,
        -1.31208072e+00],
       [-9.06839920e-01,  1.49274053e+00, -1.28103155e+00,
        -1.05539418e+00],
       [-1.13740989e+00,  1.11030287e-01, -1.28103155e+00,
        -1.44042398e+00],
       [ 4.76579890e-01, -3.49539793e-01,  1.00609787e+00,
         7.41411549e-01],
       [-9.98450310e-02, -8.10109874e-01,  1.69343206e-01,
        -2.85334584e-01],
       [ 2.09056967e+00,  1.72302557e+00,  1.61971796e+00,
         1.25478461e+00],
       [-1.48326484e+00,  3.41315328e-01, -1.33681519e+00,
        -1.31208072e+00]])

In [109]:
from sklearn.model_selection import train_test_split

In [110]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('TARGET', axis=1).values,df['TARGET'].values,test_size=0.25, random_state = 0)

In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
lg = LogisticRegression()
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)

In [113]:
pd.DataFrame(data=list(zip(y_test,y_pred)),columns=['y','y-hat'])

    y  y-hat
0   2      2
1   1      1
2   0      0
3   2      2
4   0      0
5   2      2
6   0      0
7   1      1
8   1      1
9   1      1
10  2      2
11  1      1
12  1      1
13  1      1
14  1      1
15  0      0
16  1      2
17  1      1
18  0      0
19  0      0
20  2      2
21  1      2
22  0      0
23  0      0
24  2      2
25  0      0
26  0      0
27  1      1
28  1      1
29  0      0
30  2      2
31  1      2
32  0      0
33  2      2
34  2      2
35  1      2
36  0      0
37  1      2

In [114]:
X_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.1, 1.5, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.7, 3.8, 1.7, 0.3],
       [6. , 2.7, 5.1, 1.6]])

In [115]:
X_test.shape

(38, 4)

In [116]:
from sklearn.metrics import confusion_matrix

In [117]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 11,  5],
       [ 0,  0,  9]], dtype=int64)

In [118]:
from mlxtend.plotting import plot_decision_regions

In [119]:
# plot_decision_regions(X_test, y_test, clf=lg,legend=2) #for more than two features we cannot visualize

In [120]:
# plot_decision_regions(X_train, y_train, clf=lg,legend=2)

In [121]:
from sklearn.neighbors import KNeighborsClassifier

In [122]:
df.head(9)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),TARGET
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0

In [123]:
KNe = KNeighborsClassifier(n_neighbors=4) # 5 is default value
KNe.fit(X_train,y_train)
y_pred = KNe.predict(X_test)
pd.DataFrame(data=list(zip(y_test,y_pred)),columns=['y','y-hat'])

    y  y-hat
0   2      2
1   1      1
2   0      0
3   2      2
4   0      0
5   2      2
6   0      0
7   1      1
8   1      1
9   1      1
10  2      2
11  1      1
12  1      1
13  1      1
14  1      1
15  0      0
16  1      1
17  1      1
18  0      0
19  0      0
20  2      2
21  1      1
22  0      0
23  0      0
24  2      2
25  0      0
26  0      0
27  1      1
28  1      1
29  0      0
30  2      2
31  1      1
32  0      0
33  2      2
34  2      2
35  1      1
36  0      0
37  1      2

In [132]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]], dtype=int64)

In [133]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),TARGET
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

## Naive Bayes

In [128]:
from sklearn.naive_bayes import GaussianNB #gaussian because it has gaussian curve

In [129]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)

In [130]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [131]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]], dtype=int64)