In [1]:
import numpy as np

In [2]:
import pandas as pd

In [9]:
df=pd.read_csv('/home/vins/Documents/jupyter_scripts/dataset/dataset_Facebook.csv',sep=';')

In [10]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [17]:
col_list=list(df.columns)

In [18]:
col_list

['Page total likes',
 'Type',
 'Category',
 'Post Month',
 'Post Weekday',
 'Post Hour',
 'Paid',
 'Lifetime Post Total Reach',
 'Lifetime Post Total Impressions',
 'Lifetime Engaged Users',
 'Lifetime Post Consumers',
 'Lifetime Post Consumptions',
 'Lifetime Post Impressions by people who have liked your Page',
 'Lifetime Post reach by people who like your Page',
 'Lifetime People who have liked your Page and engaged with your post',
 'comment',
 'like',
 'share',
 'Total Interactions']

In [20]:
for i in col_list:
    print i

Page total likes
Type
Category
Post Month
Post Weekday
Post Hour
Paid
Lifetime Post Total Reach
Lifetime Post Total Impressions
Lifetime Engaged Users
Lifetime Post Consumers
Lifetime Post Consumptions
Lifetime Post Impressions by people who have liked your Page
Lifetime Post reach by people who like your Page
Lifetime People who have liked your Page and engaged with your post
comment
like
share
Total Interactions

In [21]:
df.head(5)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [22]:
df.tail(5)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [24]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [25]:
df.tail

<bound method DataFrame.tail of      Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
5              139441  Status         2          12             1          9
6              139441   Photo         3          12             1          3
7              139441   Photo         3          12             7          9
8              139441  Status         2          12             7          3
9              139441   Photo         3          12             6         10
10             139441  Status         2          12             5         10
11             139441   Photo         2          12             5         10
12             139441   Photo         2          12             5         10
13             139441   Photo         2          12             5          3
14             138414   Photo         2          12             4          5
15             138414  Status         2          12             3         10
16             138414   Photo         3          12             3          3
17             138414   Photo         1          12             2         12
18             138414  Status         3          12             2          3
19             138414   Photo         3          12             1         11
20             138414   Photo         2          12             1          3
21             138414   Photo         1          12             7         10
22             138414    Link         1          12             7         10
23             138414   Photo         3          12             7          3
24             138414  Status         2          12             6         10
25             138458  Status         2          12             6          3
26             138458  Status         2          12             5         11
27             138458   Photo         3          12             5          3
28             138895   Photo         2          12             5          3
29             138895   Video         1          12             4         11
..                ...     ...       ...         ...           ...        ...
470             91437    Link         1           2             3         13
471             91330   Photo         3           2             3          3
472             91223   Photo         1           2             2         13
473             91116   Photo         3           2             2          4
474             91009   Photo         1           2             1         12
475             86909   Photo         3           1             6         16
476             86909   Photo         1           1             6         10
477             86909    Link         1           1             6          4
478             86909   Photo         3           1             5         13
479             86909   Photo         3           1             5          4
480             86909   Photo         2           1             4         11
481             86491    Link         1           1             4          4
482             86491   Photo         3           1             3         10
483             86491   Photo         2           1             3          3
484             86491   Photo         3           1             2          7
485             86491    Link         1           1             2          2
486             85979   Photo         3           1             1         12
487             85979   Photo         3           1             1          2
488             85979   Photo         3           1             7         10
489             85979   Photo         3           1             7          2
490             85979   Photo         3           1             6         11
491             85979   Photo         3           1             6          3
492             85979    Link         1           1             5         11
493             85093   Photo         3           1             1          2
494             85093   Photo         3           1             7         10
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
1     0.0                      10460                            19057
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
5     0.0                      10472                            20849
6     1.0                      11692                            19479
7     1.0                      13720                            24137
8     0.0                      11844                            22538
9     0.0                       4694                             8668
10    0.0                      21744                            42334
11    0.0                       3112                             5590
12    0.0                       2847                             5133
13    0.0                       2549                             4896
14    1.0                      22784                            39941
15    0.0                      10060                            19680
16    0.0                       1722                             2981
17    1.0                      53264                           111785
18    0.0                       3930                             7509
19    0.0                       1591                             2825
20    0.0                       2848                             5066
21    0.0                       1384                             2467
22    0.0                       3454                             6853
23    0.0                       2723                             4888
24    0.0                       8488                            15294
25    0.0                       8284                            15104
26    0.0                      19552                            34143
27    0.0                       2478                             4306
28    0.0                       9560                            18264
29    1.0                      36208                            61262
..    ...                        ...                              ...
470   0.0                       9356                            14986
471   0.0                       7732                            13264
472   0.0                       5240                             8893
473   1.0                       7132                            12060
474   0.0                      21928                            39641
475   1.0                       5754                             9238
476   1.0                      37088                            10966
477   0.0                      39600                             7927
478   0.0                       5536                             8745
479   0.0                       6056                            10325
480   0.0                      11484                            20696
481   1.0                       4938                             7910
482   0.0                      66784                             9456
483   0.0                       5526                             8779
484   0.0                       5040                             8367
485   0.0                       5168                             8371
486   0.0                       5034                             8030
487   0.0                       4908                             7491
488   0.0                       9700                            17442
489   0.0                       4800                             7754
490   0.0                       5280                             8703
491   1.0                       6184                            10228
492   0.0                      45920                             5808
493   0.0                       8412                            13960
494   0.0                       5400                             9218
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   NaN                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
5                      1191                     1073
6                       481                      265
7                       537                      232
8                      1530                     1407
9                       280                      183
10                     4258                     4100
11                      208                      127
12                      193                      115
13                      249                      134
14                      887                      337
15                     1264                     1209
16                      163                      123
17                     1706                     1103
18                      130                       86
19                      121                       88
20                      200                      142
21                       15                       15
22                      118                      104
23                      176                      118
24                     1341                     1270
25                     1521                     1462
26                     2806                     2531
27                      212                      124
28                      973                      559
29                     1141                     1068
..                      ...                      ...
470                     448                      381
471                    1066                     1002
472                     857                      837
473                    1004                      944
474                    1512                     1479
475                    1179                     1143
476                    2728                     2288
477                     572                      496
478                    1141                     1099
479                    1117                     1078
480                    1762                     1635
481                      66                       63
482                    2969                     2833
483                    1096                     1058
484                    1062                     1023
485                      66                       59
486                    1020                      993
487                     957                      937
488                    1407                     1271
489                     975                      938
490                     951                      911
491                     956                      901
492                     753                      655
493                    1179                     1111
494                     810                      756
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
5                          1389
6                           364
7                           305
8                          1692
9                           250
10                         4540
11                          145
12                          133
13                          168
14                          417
15                         1425
16                          148
17                         1655
18                          112
19                          111
20                          184
21                           20
22                          130
23                          143
24                         1489
25                         1711
26                         3420
27                          149
28                          885
29                         1728
..                          ...
470                         505
471                        1336
472                        1020
473                        1226
474                        1837
475                        1452
476                        3183
477                         581
478                        1461
479                        1427
480                        2741
481                          70
482                        3645
483                        1399
484                        1348
485                          71
486                        1243
487                        1153
488                        2007
489                        1278
490                        1237
491                        1140
492                         763
493                        1632
494                        1003
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
5                                                16034
6                                                15432
7                                                19728
8                                                15220
9                                                 4309
10                                               37849
11                                                3887
12                                                3779
13                                                3631
14                                               34415
15                                               17272
16                                                1868
17                                               92512
18                                                5009
19                                                2116
20                                                3561
21                                                2196
22                                                6282
23                                                2964
24                                                9684
25                                               10266
26                                               17748
27                                                2612
28                                                9217
29                                               30131
..                                                 ...
470                                              13919
471                                               8753
472                                               7420
473                                               8294
474                                               6338
475                                               6101
476                                              66311
477                                              12522
478                                               5225
479                                               6823
480                                               8774
481                                               6625
482                                              17809
483                                               5732
484                                               5485
485                                               7041
486                                               5340
487                                               4642
488                                               8872
489                                               4932
490                                               5757
491                                               6085
492                                              15766
493                                               8632
494                                               5654
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
5                                                7852
6                                                9328
7                                               11056
8                                                7912
9                                                2324
10                                              18952
11                                               2174
12                                               2072
13                                               1917
14                                              19312
15                                               8548
16                                               1050
17                                              39776
18                                               2410
19                                               1161
20                                               1963
21                                               1172
22                                               3100
23                                               1621
24                                               5244
25                                               5372
26                                               9824
27                                               1443
28                                               4748
29                                              14112
..                                                ...
470                                              8460
471                                              4880
472                                              4232
473                                              4736
474                                              3672
475                                              3546
476                                             34352

In [28]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [33]:
df.Type

0       Photo
1      Status
2       Photo
3       Photo
4       Photo
5      Status
6       Photo
7       Photo
8      Status
9       Photo
10     Status
11      Photo
12      Photo
13      Photo
14      Photo
15     Status
16      Photo
17      Photo
18     Status
19      Photo
20      Photo
21      Photo
22       Link
23      Photo
24     Status
25     Status
26     Status
27      Photo
28      Photo
29      Video
        ...
470      Link
471     Photo
472     Photo
473     Photo
474     Photo
475     Photo
476     Photo
477      Link
478     Photo
479     Photo
480     Photo
481      Link
482     Photo
483     Photo
484     Photo
485      Link
486     Photo
487     Photo
488     Photo
489     Photo
490     Photo
491     Photo
492      Link
493     Photo
494     Photo
495     Photo
496     Photo
497     Photo
498     Photo
499     Photo
Name: Type, Length: 500, dtype: object

In [35]:
df.groupby('Type').sum()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,2559990,25,145,94,126,6.0,407981,631960,7542,6439,8230,245269,143976,4632,62,1613.0,284.0,1959
Photo,52122877,817,2899,1750,3407,119.0,5596709,12351656,348871,294124,553385,6995978,2581178,216112,3192,77610.0,11461.0,92263
Status,5969117,91,408,206,326,10.0,588550,1091001,91810,87730,127749,839892,445886,77393,401,7952.0,1414.0,9767
Video,945104,7,67,25,61,4.0,358440,718357,11949,11093,18201,302049,121704,6856,86,1620.0,365.0,2071

In [44]:
df.groupby('Type').count()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
Type,,,,,,,,,,,,,,,,,,
Link,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
Photo,426,426,426,426,426,425,426,426,426,426,426,426,426,426,426,425,422,426
Status,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45,45
Video,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7

In [48]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [49]:
col_list

['Page total likes',
 'Type',
 'Category',
 'Post Month',
 'Post Weekday',
 'Post Hour',
 'Paid',
 'Lifetime Post Total Reach',
 'Lifetime Post Total Impressions',
 'Lifetime Engaged Users',
 'Lifetime Post Consumers',
 'Lifetime Post Consumptions',
 'Lifetime Post Impressions by people who have liked your Page',
 'Lifetime Post reach by people who like your Page',
 'Lifetime People who have liked your Page and engaged with your post',
 'comment',
 'like',
 'share',
 'Total Interactions']

In [59]:
df[df['Lifetime Post Total Impressions']>7000]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
30,138895,Photo,2,12,4,2,0.0,4940,9390,385,306,501,5860,2930,273,33,107.0,22.0,162
32,138895,Photo,3,12,3,3,0.0,5280,9578,368,237,345,4480,2422,268,2,155.0,47.0,204
34,138895,Photo,1,12,2,3,0.0,3766,7149,298,260,431,5782,2938,244,2,56.0,17.0,75
35,138895,Photo,2,12,1,11,0.0,4512,7808,423,284,431,5183,2954,316,6,172.0,21.0,199
37,138895,Photo,1,12,7,10,1.0,19800,28663,479,424,805,5187,2752,248,16,76.0,8.0,100
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
40,138895,Status,2,12,6,11,0.0,13280,24198,2055,1912,2720,17627,9344,1716,7,216.0,39.0,262
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
42,138353,Photo,1,12,5,10,0.0,7268,13989,2087,2079,12074,13544,7096,1975,7,26.0,3.0,36
44,138353,Photo,1,12,4,11,0.0,4284,8387,355,316,513,7283,3634,291,0,47.0,11.0,58
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
46,138353,Status,1,12,3,11,0.0,16576,30612,3572,3464,4802,24363,12888,3014,4,174.0,36.0,214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,91651,Photo,1,2,4,12,0.0,15288,31467,1573,1401,2110,28247,13312,1052,5,264.0,36.0,305
469,91544,Photo,3,2,4,3,0.0,9528,16779,1245,1175,1725,11885,6672,729,10,193.0,61.0,264
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

NameError: name 'df' is not defined