In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('PUBG_Player_Statistics.csv')

In [4]:
df.head()

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,4295917.30,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,3935265.63,5589608.74,1871.89,3011.87,725.44,1766,210,2193,292977.07,1897
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,2738998.00,3796916.00,2154.62,5578.41,587.28,1214,142,1252,181106.90,1057
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,2347295.00,3220260.00,2098.47,5642.54,546.10,1245,120,923,160029.80,1077

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87898 entries, 0 to 87897
Columns: 152 entries, player_name to squad_DBNOs
dtypes: float64(83), int64(68), object(1)
memory usage: 101.9+ MB

In [6]:
df.columns.values

array(['player_name', 'tracker_id', 'solo_KillDeathRatio',
       'solo_WinRatio', 'solo_TimeSurvived', 'solo_RoundsPlayed',
       'solo_Wins', 'solo_WinTop10Ratio', 'solo_Top10s',
       'solo_Top10Ratio', 'solo_Losses', 'solo_Rating', 'solo_BestRating',
       'solo_DamagePg', 'solo_HeadshotKillsPg', 'solo_HealsPg',
       'solo_KillsPg', 'solo_MoveDistancePg', 'solo_RevivesPg',
       'solo_RoadKillsPg', 'solo_TeamKillsPg', 'solo_TimeSurvivedPg',
       'solo_Top10sPg', 'solo_Kills', 'solo_Assists', 'solo_Suicides',
       'solo_TeamKills', 'solo_HeadshotKills', 'solo_HeadshotKillRatio',
       'solo_VehicleDestroys', 'solo_RoadKills', 'solo_DailyKills',
       'solo_WeeklyKills', 'solo_RoundMostKills', 'solo_MaxKillStreaks',
       'solo_WeaponAcquired', 'solo_Days', 'solo_LongestTimeSurvived',
       'solo_MostSurvivalTime', 'solo_AvgSurvivalTime', 'solo_WinPoints',
       'solo_WalkDistance', 'solo_RideDistance', 'solo_MoveDistance',
       'solo_AvgWalkDistance', 'solo_AvgRideDistance', 'solo_LongestKill',
       'solo_Heals', 'solo_Revives', 'solo_Boosts', 'solo_DamageDealt',
       'solo_DBNOs', 'duo_KillDeathRatio', 'duo_WinRatio',
       'duo_TimeSurvived', 'duo_RoundsPlayed', 'duo_Wins',
       'duo_WinTop10Ratio', 'duo_Top10s', 'duo_Top10Ratio', 'duo_Losses',
       'duo_Rating', 'duo_BestRating', 'duo_DamagePg',
       'duo_HeadshotKillsPg', 'duo_HealsPg', 'duo_KillsPg',
       'duo_MoveDistancePg', 'duo_RevivesPg', 'duo_RoadKillsPg',
       'duo_TeamKillsPg', 'duo_TimeSurvivedPg', 'duo_Top10sPg',
       'duo_Kills', 'duo_Assists', 'duo_Suicides', 'duo_TeamKills',
       'duo_HeadshotKills', 'duo_HeadshotKillRatio',
       'duo_VehicleDestroys', 'duo_RoadKills', 'duo_DailyKills',
       'duo_WeeklyKills', 'duo_RoundMostKills', 'duo_MaxKillStreaks',
       'duo_WeaponAcquired', 'duo_Days', 'duo_LongestTimeSurvived',
       'duo_MostSurvivalTime', 'duo_AvgSurvivalTime', 'duo_WinPoints',
       'duo_WalkDistance', 'duo_RideDistance', 'duo_MoveDistance',
       'duo_AvgWalkDistance', 'duo_AvgRideDistance', 'duo_LongestKill',
       'duo_Heals', 'duo_Revives', 'duo_Boosts', 'duo_DamageDealt',
       'duo_DBNOs', 'squad_KillDeathRatio', 'squad_WinRatio',
       'squad_TimeSurvived', 'squad_RoundsPlayed', 'squad_Wins',
       'squad_WinTop10Ratio', 'squad_Top10s', 'squad_Top10Ratio',
       'squad_Losses', 'squad_Rating', 'squad_BestRating',
       'squad_DamagePg', 'squad_HeadshotKillsPg', 'squad_HealsPg',
       'squad_KillsPg', 'squad_MoveDistancePg', 'squad_RevivesPg',
       'squad_RoadKillsPg', 'squad_TeamKillsPg', 'squad_TimeSurvivedPg',
       'squad_Top10sPg', 'squad_Kills', 'squad_Assists', 'squad_Suicides',
       'squad_TeamKills', 'squad_HeadshotKills',
       'squad_HeadshotKillRatio', 'squad_VehicleDestroys',
       'squad_RoadKills', 'squad_DailyKills', 'squad_WeeklyKills',
       'squad_RoundMostKills', 'squad_MaxKillStreaks',
       'squad_WeaponAcquired', 'squad_Days', 'squad_LongestTimeSurvived',
       'squad_MostSurvivalTime', 'squad_AvgSurvivalTime',
       'squad_WinPoints', 'squad_WalkDistance', 'squad_RideDistance',
       'squad_MoveDistance', 'squad_AvgWalkDistance',
       'squad_AvgRideDistance', 'squad_LongestKill', 'squad_Heals',
       'squad_Revives', 'squad_Boosts', 'squad_DamageDealt',
       'squad_DBNOs'], dtype=object)

In [7]:
df[df['solo_WinRatio']>2].head()

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,4295917.30,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,2738998.00,3796916.00,2154.62,5578.41,587.28,1214,142,1252,181106.90,1057
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,2347295.00,3220260.00,2098.47,5642.54,546.10,1245,120,923,160029.80,1077
5,coldoxygen,33313,5.73,31.25,22003.22,16,5,0.50,10,62.5,...,3218436.00,4733977.00,2078.93,4414.86,1212.76,2023,195,2307,238640.00,1450

In [8]:
df['solo_WinRatio'].max()

100.0

In [56]:
df[df['solo_KillDeathRatio']>5].sort_values('solo_KillDeathRatio', ascending=False).head()

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
3739,ContinuousStrike,207460,100.0,85.71,12631.47,7,6,0.92,7,100.0,...,94403.11,183782.18,2578.28,2368.43,404.38,75,4,88,31836.55,227
53447,AcklesT__T,185283,88.0,85.71,26110.78,14,12,0.96,13,92.9,...,78693.52,141500.24,1458.88,2070.55,547.51,40,9,86,27930.66,213
31627,X-XRAYYY,30607,76.0,75.00,5340.95,4,3,0.50,3,75.0,...,59710.85,123688.54,1599.44,1492.77,543.00,26,6,60,34352.52,272
5122,kolbaska666,163254,49.0,80.00,9003.11,5,4,0.80,5,100.0,...,184734.01,291351.74,1222.01,2667.95,399.88,233,34,114,35659.16,238
1689,Six13,48879,48.0,66.67,4324.27,3,2,1.00,2,66.7,...,126426.47,383143.23,2844.96,1094.47,584.02,131,8,157,101306.56,732

In [10]:
df['solo_KillDeathRatio'].max()

100.0

In [11]:
df[df['solo_KillDeathRatio']==100]

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
3739,ContinuousStrike,207460,100.0,85.71,12631.47,7,6,0.92,7,100.0,...,94403.11,183782.18,2578.28,2368.43,404.38,75,4,88,31836.55,227

In [12]:
df.shape

(87898, 152)

In [13]:
x = df.shape[0]
x

87898

In [14]:
r = range(1,x)
r

range(1, 87898)

In [15]:
df.iloc[1:3]

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,4295917.30,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,3935265.63,5589608.74,1871.89,3011.87,725.44,1766,210,2193,292977.07,1897

In [62]:
df.iloc[1].isnull

<bound method Series.isnull of player_name                    Blackwalk
tracker_id                          8199
solo_KillDeathRatio                 4.41
solo_WinRatio                      18.18
solo_TimeSurvived                33014.9
solo_RoundsPlayed                     33
solo_Wins                              6
solo_WinTop10Ratio                  0.36
solo_Top10s                           11
solo_Top10Ratio                     33.3
solo_Losses                           27
solo_Rating                      1884.53
solo_BestRating                  1860.74
solo_DamagePg                     393.04
solo_HeadshotKillsPg                1.27
solo_HealsPg                        1.82
solo_KillsPg                        3.61
solo_MoveDistancePg              5021.41
solo_RevivesPg                         0
solo_RoadKillsPg                    0.06
solo_TeamKillsPg                       0
solo_TimeSurvivedPg              1000.45
solo_Top10sPg                       0.33
solo_Kills                           119
solo_Assists                           2
solo_Suicides                          0
solo_TeamKills                         0
solo_HeadshotKills                    42
solo_HeadshotKillRatio              0.35
solo_VehicleDestroys                   3
                                ...
squad_Top10sPg                      0.89
squad_Kills                         2201
squad_Assists                        964
squad_Suicides                         1
squad_TeamKills                        3
squad_HeadshotKills                  439
squad_HeadshotKillRatio              0.2
squad_VehicleDestroys                 44
squad_RoadKills                       22
squad_DailyKills                      84
squad_WeeklyKills                    405
squad_RoundMostKills                  14
squad_MaxKillStreaks                   5
squad_WeaponAcquired                   0
squad_Days                            44
squad_LongestTimeSurvived        2192.81
squad_MostSurvivalTime           2192.81
squad_AvgSurvivalTime            1570.51
squad_WinPoints                     4058
squad_WalkDistance           1.75587e+06
squad_RideDistance           4.29592e+06
squad_MoveDistance           6.05178e+06
squad_AvgWalkDistance            2422.48
squad_AvgRideDistance            6009.73
squad_LongestKill                 734.85
squad_Heals                         2041
squad_Revives                        276
squad_Boosts                        2340
squad_DamageDealt                 269796
squad_DBNOs                         1724
Name: 1, Length: 152, dtype: object>

# Checking Null value (takes lot of time and is inefficient) donot run

for i in r:
    if df.iloc[i].isnull==True:
        print('Empty : ', df.iloc[i])
print('Null value checked successfully')

In [19]:
df.head()

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448
1,Blackwalk,8199,4.41,18.18,33014.86,33,6,0.36,11,33.3,...,4295917.30,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724
2,mercedes_benz,4454,3.60,0.00,4330.44,5,0,0.00,1,20.0,...,3935265.63,5589608.74,1871.89,3011.87,725.44,1766,210,2193,292977.07,1897
3,DORA,7729,14.00,50.00,13421.82,8,4,0.67,6,75.0,...,2738998.00,3796916.00,2154.62,5578.41,587.28,1214,142,1252,181106.90,1057
4,n2tstar,0,10.50,33.33,9841.04,6,2,0.40,5,83.3,...,2347295.00,3220260.00,2098.47,5642.54,546.10,1245,120,923,160029.80,1077

In [20]:
df.as_matrix()

C:\Users\Ramesh Pradhan\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':

array([['BreakNeck', 4405, 3.14, ..., 1884, 242132.73, 1448],
       ['Blackwalk', 8199, 4.41, ..., 2340, 269795.75, 1724],
       ['mercedes_benz', 4454, 3.6, ..., 2193, 292977.07, 1897],
       ...,
       ['Dertydann', 178547, 1.0, ..., 95, 15939.11, 92],
       ['Neferhor', 126589, 5.1, ..., 317, 56870.07, 350],
       ['pepperedangus', 66362, 0.83, ..., 150, 19769.59, 140]],
      dtype=object)

In [21]:
pd.DataFrame(df.as_matrix()).head()

C:\Users\Ramesh Pradhan\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':

,0,1,2,3,4,5,6,7,8,9,...,142,143,144,145,146,147,148,149,150,151
0,BreakNeck,4405,3.14,17.65,18469.1,17,3,0.83,4,23.5,...,3.75159e+06,5.19479e+06,2626.97,4372.64,536.98,2186,234,1884,242133,1448
1,Blackwalk,8199,4.41,18.18,33014.9,33,6,0.36,11,33.3,...,4.29592e+06,6.05178e+06,2422.48,6009.73,734.85,2041,276,2340,269796,1724
2,mercedes_benz,4454,3.6,0,4330.44,5,0,0,1,20,...,3.93527e+06,5.58961e+06,1871.89,3011.87,725.44,1766,210,2193,292977,1897
3,DORA,7729,14,50,13421.8,8,4,0.67,6,75,...,2.739e+06,3.79692e+06,2154.62,5578.41,587.28,1214,142,1252,181107,1057
4,n2tstar,0,10.5,33.33,9841.04,6,2,0.4,5,83.3,...,2.3473e+06,3.22026e+06,2098.47,5642.54,546.1,1245,120,923,160030,1077

In [67]:
df[df.isin(['NaN'])].head()

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df.isin(['NaN']).head(2)

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
df[df['player_name'].isin(['Black','White', 'Crystal','BreakNeck'])].head(3)

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448
39143,Black,11636,2.75,9.09,25873.83,22,2,0.29,7,31.8,...,208150.10,354942.60,1790.15,2538.42,199.82,146,16,146,19903.67,121

In [24]:
print('this many columns:%d ' % len(df.columns))
df.columns

this many columns:152

Index(['player_name', 'tracker_id', 'solo_KillDeathRatio', 'solo_WinRatio',
       'solo_TimeSurvived', 'solo_RoundsPlayed', 'solo_Wins',
       'solo_WinTop10Ratio', 'solo_Top10s', 'solo_Top10Ratio',
       ...
       'squad_RideDistance', 'squad_MoveDistance', 'squad_AvgWalkDistance',
       'squad_AvgRideDistance', 'squad_LongestKill', 'squad_Heals',
       'squad_Revives', 'squad_Boosts', 'squad_DamageDealt', 'squad_DBNOs'],
      dtype='object', length=152)

In [25]:
df[df['solo_WinRatio'].isnull()].head(10)

Empty DataFrame
Columns: [player_name, tracker_id, solo_KillDeathRatio, solo_WinRatio, solo_TimeSurvived, solo_RoundsPlayed, solo_Wins, solo_WinTop10Ratio, solo_Top10s, solo_Top10Ratio, solo_Losses, solo_Rating, solo_BestRating, solo_DamagePg, solo_HeadshotKillsPg, solo_HealsPg, solo_KillsPg, solo_MoveDistancePg, solo_RevivesPg, solo_RoadKillsPg, solo_TeamKillsPg, solo_TimeSurvivedPg, solo_Top10sPg, solo_Kills, solo_Assists, solo_Suicides, solo_TeamKills, solo_HeadshotKills, solo_HeadshotKillRatio, solo_VehicleDestroys, solo_RoadKills, solo_DailyKills, solo_WeeklyKills, solo_RoundMostKills, solo_MaxKillStreaks, solo_WeaponAcquired, solo_Days, solo_LongestTimeSurvived, solo_MostSurvivalTime, solo_AvgSurvivalTime, solo_WinPoints, solo_WalkDistance, solo_RideDistance, solo_MoveDistance, solo_AvgWalkDistance, solo_AvgRideDistance, solo_LongestKill, solo_Heals, solo_Revives, solo_Boosts, solo_DamageDealt, solo_DBNOs, duo_KillDeathRatio, duo_WinRatio, duo_TimeSurvived, duo_RoundsPlayed, duo_Wins, duo_WinTop10Ratio, duo_Top10s, duo_Top10Ratio, duo_Losses, duo_Rating, duo_BestRating, duo_DamagePg, duo_HeadshotKillsPg, duo_HealsPg, duo_KillsPg, duo_MoveDistancePg, duo_RevivesPg, duo_RoadKillsPg, duo_TeamKillsPg, duo_TimeSurvivedPg, duo_Top10sPg, duo_Kills, duo_Assists, duo_Suicides, duo_TeamKills, duo_HeadshotKills, duo_HeadshotKillRatio, duo_VehicleDestroys, duo_RoadKills, duo_DailyKills, duo_WeeklyKills, duo_RoundMostKills, duo_MaxKillStreaks, duo_WeaponAcquired, duo_Days, duo_LongestTimeSurvived, duo_MostSurvivalTime, duo_AvgSurvivalTime, duo_WinPoints, duo_WalkDistance, duo_RideDistance, duo_MoveDistance, duo_AvgWalkDistance, duo_AvgRideDistance, duo_LongestKill, duo_Heals, duo_Revives, duo_Boosts, ...]
Index: []

[0 rows x 152 columns]

In [71]:
len(df.columns)

152

In [81]:
na = df.isnull().sum().sort_values(ascending=False)
na[na>0]
#prints if columns have any null value associated

Series([], dtype: int64)

In [83]:
df.head(1)

,player_name,tracker_id,solo_KillDeathRatio,solo_WinRatio,solo_TimeSurvived,solo_RoundsPlayed,solo_Wins,solo_WinTop10Ratio,solo_Top10s,solo_Top10Ratio,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,BreakNeck,4405,3.14,17.65,18469.14,17,3,0.83,4,23.5,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448

In [85]:
solo_cols = [x for x in df.columns if ('solo' in x)]
solo_cols

['solo_KillDeathRatio',
 'solo_WinRatio',
 'solo_TimeSurvived',
 'solo_RoundsPlayed',
 'solo_Wins',
 'solo_WinTop10Ratio',
 'solo_Top10s',
 'solo_Top10Ratio',
 'solo_Losses',
 'solo_Rating',
 'solo_BestRating',
 'solo_DamagePg',
 'solo_HeadshotKillsPg',
 'solo_HealsPg',
 'solo_KillsPg',
 'solo_MoveDistancePg',
 'solo_RevivesPg',
 'solo_RoadKillsPg',
 'solo_TeamKillsPg',
 'solo_TimeSurvivedPg',
 'solo_Top10sPg',
 'solo_Kills',
 'solo_Assists',
 'solo_Suicides',
 'solo_TeamKills',
 'solo_HeadshotKills',
 'solo_HeadshotKillRatio',
 'solo_VehicleDestroys',
 'solo_RoadKills',
 'solo_DailyKills',
 'solo_WeeklyKills',
 'solo_RoundMostKills',
 'solo_MaxKillStreaks',
 'solo_WeaponAcquired',
 'solo_Days',
 'solo_LongestTimeSurvived',
 'solo_MostSurvivalTime',
 'solo_AvgSurvivalTime',
 'solo_WinPoints',
 'solo_WalkDistance',
 'solo_RideDistance',
 'solo_MoveDistance',
 'solo_AvgWalkDistance',
 'solo_AvgRideDistance',
 'solo_LongestKill',
 'solo_Heals',
 'solo_Revives',
 'solo_Boosts',
 'solo_DamageDealt',
 'solo_DBNOs']

In [ ]:
df_feat = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])

In [122]:
solo_df = pd.DataFrame([df[solo_cols] for x in solo_cols], columns=df[solo_cols])

ValueError: Shape of passed values is (1, 50), indices imply (87898, 50)

In [118]:
solo_df

                                                    0
0          solo_KillDeathRatio  solo_WinRatio  sol...
1          solo_KillDeathRatio  solo_WinRatio  sol...
2          solo_KillDeathRatio  solo_WinRatio  sol...
3          solo_KillDeathRatio  solo_WinRatio  sol...
4          solo_KillDeathRatio  solo_WinRatio  sol...
5          solo_KillDeathRatio  solo_WinRatio  sol...
6          solo_KillDeathRatio  solo_WinRatio  sol...
7          solo_KillDeathRatio  solo_WinRatio  sol...
8          solo_KillDeathRatio  solo_WinRatio  sol...
9          solo_KillDeathRatio  solo_WinRatio  sol...
10         solo_KillDeathRatio  solo_WinRatio  sol...
11         solo_KillDeathRatio  solo_WinRatio  sol...
12         solo_KillDeathRatio  solo_WinRatio  sol...
13         solo_KillDeathRatio  solo_WinRatio  sol...
14         solo_KillDeathRatio  solo_WinRatio  sol...
15         solo_KillDeathRatio  solo_WinRatio  sol...
16         solo_KillDeathRatio  solo_WinRatio  sol...
17         solo_KillDeathRatio  solo_WinRatio  sol...
18         solo_KillDeathRatio  solo_WinRatio  sol...
19         solo_KillDeathRatio  solo_WinRatio  sol...
20         solo_KillDeathRatio  solo_WinRatio  sol...
21         solo_KillDeathRatio  solo_WinRatio  sol...
22         solo_KillDeathRatio  solo_WinRatio  sol...
23         solo_KillDeathRatio  solo_WinRatio  sol...
24         solo_KillDeathRatio  solo_WinRatio  sol...
25         solo_KillDeathRatio  solo_WinRatio  sol...
26         solo_KillDeathRatio  solo_WinRatio  sol...
27         solo_KillDeathRatio  solo_WinRatio  sol...
28         solo_KillDeathRatio  solo_WinRatio  sol...
29         solo_KillDeathRatio  solo_WinRatio  sol...
30         solo_KillDeathRatio  solo_WinRatio  sol...
31         solo_KillDeathRatio  solo_WinRatio  sol...
32         solo_KillDeathRatio  solo_WinRatio  sol...
33         solo_KillDeathRatio  solo_WinRatio  sol...
34         solo_KillDeathRatio  solo_WinRatio  sol...
35         solo_KillDeathRatio  solo_WinRatio  sol...
36         solo_KillDeathRatio  solo_WinRatio  sol...
37         solo_KillDeathRatio  solo_WinRatio  sol...
38         solo_KillDeathRatio  solo_WinRatio  sol...
39         solo_KillDeathRatio  solo_WinRatio  sol...
40         solo_KillDeathRatio  solo_WinRatio  sol...
41         solo_KillDeathRatio  solo_WinRatio  sol...
42         solo_KillDeathRatio  solo_WinRatio  sol...
43         solo_KillDeathRatio  solo_WinRatio  sol...
44         solo_KillDeathRatio  solo_WinRatio  sol...
45         solo_KillDeathRatio  solo_WinRatio  sol...
46         solo_KillDeathRatio  solo_WinRatio  sol...
47         solo_KillDeathRatio  solo_WinRatio  sol...
48         solo_KillDeathRatio  solo_WinRatio  sol...
49         solo_KillDeathRatio  solo_WinRatio  sol...

In [115]:
s = df['solo_Assists']

In [113]:
s.head()

0    1
1    2
2    1
3    3
4    0
Name: solo_Assists, dtype: int64

AttributeError: 'Series' object has no attribute 'merge'

In [27]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [28]:
c.shape

(3, 3)

In [29]:
print(c)

[[-6.00369845e-01 -5.47144406e-01  4.15121644e-01]
 [ 1.04729379e-02  1.23784212e-03 -1.85303587e-02]
 [ 4.24918717e-01  1.32881589e+00 -1.52794955e+00]]

In [30]:
a

array([[-1.09927772, -1.00182189,  0.7600881 ],
       [ 1.09853382,  0.12984049, -1.94369772],
       [ 0.32193853,  1.00677381, -1.1576469 ]])

In [31]:
b

array([[0.54614938],
       [0.00953356],
       [1.3198753 ]])

In [35]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2)

In [41]:
a= np.random.randn(3,4)
b= np.random.randn(4,1)

print (a,'\n')
print (b)

[[ 1.84762284  0.5562969  -0.39652323  0.52944586]
 [ 1.5961696  -0.81842467  1.00933165 -0.33707545]
 [ 0.10734078 -0.5986554   0.18796363  0.80023951]]

[[-0.1439611 ]
 [-1.42908344]
 [ 0.10628701]
 [ 0.37281053]]

In [42]:
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [44]:
c = a + b.T
print(c)

[[ 1.70366175 -0.87278654 -0.29023621  0.90225638]
 [ 1.45220851 -2.24750811  1.11561866  0.03573507]
 [-0.03662032 -2.02773885  0.29425064  1.17305004]]

In [46]:
c = a + b
print(c)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1)

In [47]:
c = a.T + b
print(c)

[[ 1.70366175  1.45220851 -0.03662032]
 [-0.87278654 -2.24750811 -2.02773885]
 [-0.29023621  1.11561866  0.29425064]
 [ 0.90225638  0.03573507  1.17305004]]

In [48]:
c = a.T + b.T
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (1,4)

In [49]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.73850728 -0.2993357  -0.44652071]
 [ 0.45648248 -0.3339925   0.3425478 ]
 [-0.62343264  0.18986003 -0.36125833]]

In [50]:
import numpy as np
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

C:\Users\Ramesh Pradhan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [52]:
import Python_DHT

ModuleNotFoundError: No module named 'Python_DHT'